### PR TITLE
Fix template project and bin path for cross platform use also add 	smoke test

### PR DESCRIPTION
**Pull request by ilyar**

### CODE REVIEW

**Comment by ilyar** [comment]
if ok, pliase `git merge --ff-only` more info setting project for **Merge button** and aticle "A tidy, linear Git history" https://twitter.com/m_bitsnbites/status/679757671545831426

**Comment by artemshitov** [comment]
This way requires a global installation of both babel-cli and webpack. How do we make it cross-platform while sticking to the local versions?

**Comment by ilyar** [comment]
@artemshitov all work without global install babel-cli and webpack. see 04d6f6f and logs:

- *nix - https://travis-ci.org/ilyar/dpt/builds/210560601
- windows https://ci.appveyor.com/project/ilyar/dpt/build/3

**Comment by ilyar** [comment]
@artemshitov bin running in npm scripts first search local package if no found then used global.

**Comment by ilyar** [comment]
Cool, thx. More will be useful setup `travis-ci` and `appveyor` for project.

**Pull request merged**
